### ISSUE TITLE
Dymanic capability registration not enabled, helix-editor reports

### ISSUE THREAD

**Issue by Tefached95** [vshaxe/vshaxe#595]
Hello,

I've been trying to get the LSP working with the helix editor. I've built the server as per instructions and added the following to `languages.toml`:

```toml
[[language]]
name = "haxe"
scope = "source.haxe"
injection-regex = "^Haxe$"
file-types = [ "hx", "hxml" ]
comment-token = "//"
language-servers = [ "haxe-lsp" ]
roots = [".gitignore"]

[language-server.haxe-lsp]
command = "node"
args = ["E:\\Projects\\haxe-language-server\\bin\\server.js"]

[[grammar]]
name = "haxe"
source = { git = "https://github.com/vantreeseba/tree-sitter-haxe", rev = "ca7ed7931a93a0434cd1f5d6bb6c333865fe711a" }
```

Which "works", but then trying to open a `.hx` file results in the following output in the log:
```
2023-06-14T19:08:16.693 helix_lsp::transport [ERROR] haxe-lsp err: <- StreamClosed
2023-06-14T19:08:16.766 helix_term::application [WARN] Ignoring a client/registerCapability request because dynamic capability registration is not enabled. Please report this upstream to the language server
```

If more details are needed please let me know, and thank you in advance!
